<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC9CtWBb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC9CtWBb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC9CtWBb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC9CtWBb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC9CtWBb\App_KernelDevDebugContainer([
    'container.build_hash' => 'C9CtWBb',
    'container.build_id' => '3a034bea',
    'container.build_time' => 1674723120,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC9CtWBb');
